---
# Configures labels to be automatically applied to PRs based on paths.
#
# See: https://github.com/actions/labeler

2.x:
    - maintenance/projects/js-toolkit/*
    - maintenance/projects/js-toolkit/**/*

3.x:
    - projects/js-toolkit/*
    - projects/js-toolkit/**/*

amd-loader:
    - projects/amd-loader/*
    - projects/amd-loader/**/*

changelog-generator:
    - projects/npm-tools/packages/changelog-generator/*
    - projects/npm-tools/packages/changelog-generator/**/*

eslint-config:
    - projects/eslint-config/*
    - projects/eslint-config/**/*

jest-junit-reporter:
    - projects/npm-tools/packages/jest-junit-reporter/*
    - projects/npm-tools/packages/jest-junit-reporter/**/*

js-insights:
    - projects/npm-tools/packages/js-insights/*
    - projects/npm-tools/packages/js-insights/**/*

js-publish:
    - projects/npm-tools/packages/js-publish/*
    - projects/npm-tools/packages/js-publish/**/*

js-toolkit:
    - maintenance/projects/js-toolkit/*
    - maintenance/projects/js-toolkit/**/*
    - projects/js-toolkit/*
    - projects/js-toolkit/**/*

npm-bundler-preset-liferay-dev:
    - projects/npm-tools/packages/npm-bundler-preset-liferay-dev/*
    - projects/npm-tools/packages/npm-bundler-preset-liferay-dev/**/*

npm-scripts:
    - projects/npm-tools/packages/npm-scripts/*
    - projects/npm-tools/packages/npm-scripts/**/*

npm-tools:
    - projects/npm-tools/*
    - projects/npm-tools/**/*
