before_install:
    - mkdir -p "$HOME/.yarn/bin"
    - curl -L -o "$HOME/.yarn/bin/yarn" https://github.com/yarnpkg/yarn/releases/download/v1.15.2/yarn-1.15.2.js
    - chmod +x "$HOME/.yarn/bin/yarn"
    - export PATH="$HOME/.yarn/bin:$PATH"

install:
    - yarn

language: node_js

node_js:
  - '10'

script:
    - yarn ci
